# CapCut Auto Project Creator Configuration

template_dir: "./template-config"
project_root: "."
required_structure:
  - ".locked"
  - "adjust_mask"
  - "common_attachment"
  - "draft_settings"
  - "matting"
  - "qr_upload"
  - "Resources"
  - "Resources/audioAlg"
  - "Resources/videoAlg"
  - "smart_crop"
  - "subdraft"

naming:
  pattern: "^[A-Z]\\d{4}$"
  examples: ["A0001", "B9999", "Z1234"]

assets:
  images_dir: "./assets/images"
  sounds_dir: "./assets/sounds"
  image_extensions: [".jpg", ".jpeg", ".png", ".bmp", ".webp", ".webm"]
  sound_extensions: [".mp3", ".wav", ".m4a"]

timeline:
  default_image_duration_ms: 5000   # default 5s; editable
  ordering: "numeric"               # numeric sort (1,2,3…)

transitions:
  per_cut_probability: 0.65
  duration_ms_range: [600, 800]
  # Where CapCut caches effects (override if different user/profile or non-English Windows)
  cache_root: "C:/Users/Admin/AppData/Local/CapCut/User Data/Cache/effect"
  catalog:
    - name: "Fast Swipe"
      category_id: "25822"
      category_name: "Trending"
      effect_id: "7544051798751874365"
      resource_id: "7544051798751874365"
      third_resource_id: "0"
      is_overlap: true
    - name: "Total Ban"
      category_id: "25822"
      category_name: "remen"
      effect_id: "7545400875309747517"
      resource_id: "7545400875309747517"
      third_resource_id: "0"
      is_overlap: true
    - name: "Color Glitch"
      category_id: "25822"
      category_name: "remen"
      effect_id: "6724239785205961228"
      resource_id: "6724239785205961228"
      third_resource_id: "6724239785205961228"
      is_overlap: false
    - name: "TV Glitch"
      category_id: "25822"
      category_name: "remen"
      effect_id: "7473770029234916669"
      resource_id: "7473770029234916669"
      third_resource_id: "7474958184738722321"
      is_overlap: true
    - name: "Glitchy Fade"
      category_id: "25822"
      category_name: "remen"
      effect_id: "7543568407669558581"
      resource_id: "7543568407669558581"
      third_resource_id: "0"
      is_overlap: true
    - name: "Slosh"
      category_id: "25822"
      category_name: "remen"
      effect_id: "7340902143936696834"
      resource_id: "7340902143936696834"
      third_resource_id: "7340902143936696834"
      is_overlap: true
    - name: "Colorligh"
      category_id: "25822"
      category_name: "remen"
      effect_id: "7548352051529436469"
      resource_id: "7548352051529436469"
      third_resource_id: "0"
      is_overlap: true
    - name: "Signal Glitch 2"
      category_id: "25822"
      category_name: "remen"
      effect_id: "7343854374147330562"
      resource_id: "7343854374147330562"
      third_resource_id: "7343854374147330562"
      is_overlap: false


doctor:
  autofix: true
  strict: true

ids:
  strategy: "mirror"                # replicate CapCut’s ID structure

advanced:
  max_template_size_mb: 500
  backup_on_overwrite: true
  backup_dir: "./.capcut_backups"

logging:
  level: "INFO"
  file: null
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
